import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';

const RANDOM_WORD_URL = 'https://random-word-api.herokuapp.com/word?length=5';

const Home: NextPage = () => {
  const [word, setWord] = useState('');
  const [guess, setGuess] = useState('');
  const [message, setMessage] = useState('');
  const [triesLeft, setTriesLeft] = useState(5);
  const [gameOver, setGameOver] = useState(false);

  const fetchWord = async () => {
    try {
      const res = await fetch(RANDOM_WORD_URL);
      if (!res.ok) throw new Error('Failed to fetch');
      const data: string[] = await res.json();
      setWord(data[0]);
    } catch (err) {
      console.error(err);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!word || gameOver) return;

    const normalizedGuess = guess.trim().toLowerCase();

    if (normalizedGuess === word) {
      setMessage('Correct!');
      setGameOver(true);
      return;
    }

    const remaining = triesLeft - 1;
    setTriesLeft(remaining);

    if (remaining > 0) {
      setMessage(`Wrong! You have ${remaining} ${remaining === 1 ? 'try' : 'tries'} left.`);
    } else {
      setMessage(`You lose! The word was "${word}".`);
      setGameOver(true);
    }

    setGuess('');
  };

  useEffect(() => {
    fetchWord();
  }, []);

  const handleReset = () => {
    setWord('');
    setGuess('');
    setMessage('');
    setTriesLeft(5);
    setGameOver(false);
    fetchWord();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Tokle</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

    <main className={styles.main}>
      <ConnectButton />
      
      <h1 className={styles.title}>Welcome to Tokle!</h1>
      
      <p className={styles.description}>
        A <a href="https://www.nytimes.com/games/wordle/index.html">Wordle</a>{' '}
        like game with Web3!
      </p>

      <p>Daily word: {word ? word : 'Loading...'} (for testing)</p>

      <form onSubmit={handleSubmit}>
        <input
          type="text"
          value={guess}
          onChange={(e) => setGuess(e.target.value)}
          placeholder="Enter your guess"
          className="guess-input"
          disabled={gameOver}
        />
        <button type="submit" className="guess-button" disabled={gameOver || !word}>
          Guess
        </button>
      </form>
      
      <p className="tries"> Tries left: {triesLeft}</p>

      <p className="message">{message}</p>

      {gameOver && (
        <button onClick={handleReset} className="reload-button">
          Try Again
        </button>
      )}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;

